<?xml version="1.0" encoding="utf-8"?><Database Name="ECClaimSystem" Class="dbECClaimSystemDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ThanhTran;Initial Catalog=ECClaimSystem;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ECClaimSystemConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ECClaim" Member="ECClaims">
    <Type Name="ECClaim">
      <Column Name="ClaimId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Situation" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="EffectSituation" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CircumstanceStartDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CircumstanceEndDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="OutCome" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SubmittedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FinalClosureDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ClaimStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DecisionStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DecisionDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ProcessedUser" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="HasEvidence" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="ECClaim_ECEvidence" Member="ECEvidences" ThisKey="ClaimId" OtherKey="ClaimId" Type="ECEvidence" />
      <Association Name="User_ECClaim" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccountId" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="UserFullName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="BirthDay" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FacultyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="User_ECClaim" Member="ECClaims" ThisKey="UserId" OtherKey="UserId" Type="ECClaim" />
      <Association Name="Faculty_User" Member="Faculty" ThisKey="FacultyId" OtherKey="FacultyId" Type="Faculty" IsForeignKey="true" />
      <Association Name="Role_User" Member="Role" ThisKey="RoleId" OtherKey="RoleId" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ECEvidence" Member="ECEvidences">
    <Type Name="ECEvidence">
      <Column Name="EvidenceId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EvidenceName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ClaimId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="ECClaim_ECEvidence" Member="ECClaim" ThisKey="ClaimId" OtherKey="ClaimId" Type="ECClaim" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Faculty" Member="Faculties">
    <Type Name="Faculty">
      <Column Name="FacultyId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FacultyCode" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FacultyName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Faculty_User" Member="Users" ThisKey="FacultyId" OtherKey="FacultyId" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Role_User" Member="Users" ThisKey="RoleId" OtherKey="RoleId" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.Setting" Member="Settings">
    <Type Name="Setting">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[Key]" Member="Key" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_ECClaim_GetAllECClaimsOfFaculty" Method="sp_ECClaim_GetAllECClaimsOfFaculty">
    <Parameter Name="FacultyId" Parameter="facultyId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ECClaim_GetAllECClaimsOfFacultyResult">
      <Column Name="ClaimId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Situation" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="EffectSituation" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CircumstanceStartDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CircumstanceEndDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="OutCome" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SubmittedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FinalClosureDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ClaimStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DecisionStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DecisionDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ProcessedUser" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="HasEvidence" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetECClaimOfFaculty" Method="sp_GetECClaimOfFaculty">
    <Parameter Name="FacultyId" Parameter="facultyId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_GetECClaimOfFacultyResult">
      <Column Name="ClaimId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Situation" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="EffectSituation" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CircumstanceStartDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CircumstanceEndDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="OutCome" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SubmittedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FinalClosureDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ClaimStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DecisionStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DecisionDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ProcessedUser" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="HasEvidence" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>